### ISSUE TITLE
Irreducibility of a stochastic matrix.

### ISSUE THREAD

**Issue by eborrell** [LuzieH/pytpt#41]
I have found the following proposition (Prop ) in the book "Matrix analysis" by Horn and Johnson. 
Let A \in \R^{n x n}. The following are equivalent:
- A irreducible, 
- (Id + |A|)^(n-1) > 0.

Since we are working with stochastic matrices, there might be other equivalences which are weaker than this. However, this can be easily implemented.

**Comment by eborrell** [comment]
@LuzieH Let me know what do you think.

**Comment by LuzieH** [comment]
@eborrell I didn't now this equivalence and I think it is good enough. Did you add the book reference to the check?
